# Generated by Django 3.2.6 on 2021-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0002_alter_countryinformation_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinformation',
            name='country_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
