# Generated by Django 3.2.6 on 2021-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=25)),
                ('country_code', models.CharField(max_length=15)),
                ('iso_code', models.CharField(max_length=10)),
                ('population', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('flag', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
