# Generated by Django 3.2.6 on 2021-08-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryinformation',
            name='flag',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
